# Generated by Django 3.0.5 on 2020-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_status', '0002_auto_20200109_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
